### ISSUE TITLE
update to latest linguist

### ISSUE THREAD

**Issue by yomed** [heyimalex/gh-highlight#1]
Hi, I was happy to find your repo, as I couldn't find any other code highlighting packages that use linguist. Would you consider updating this to use the latest version of linguist?  I'd like to use this with `marko`, which was added after your last update: https://github.com/github/linguist/pull/3519

**Comment by heyimalex** [comment]
For sure. I'm in the process of getting a new computer, so I can't get to this until the weekend. Will happily accept PRs tho!

**Comment by yomed** [comment]
Thanks. I did take a look at sending a PR for this, but I ended up in a rabbit hole in trying to get the linguist scripts running :confused:

**Comment by heyimalex** [comment]
New version should be up, let me know! I don't actually use this 🤷‍♂️

**Comment by yomed** [comment]
Would you need to update the `grammar` files here also? That's the part I was having trouble with. https://github.com/heyimalex/gh-highlight/tree/master/grammars

**Comment by heyimalex** [comment]
Whoops

**Comment by heyimalex** [comment]
They made the install process even more crazy so I hacked together a rebuild of the grammars special for you and hopefully it works. The kind of good news is that they started normalizing the grammars upstream. Anyway, you're literally the only person I know of who uses this, so let me know!

**Comment by yomed** [comment]
Oh wow, thanks for your help on this. It works great, except for one issue -- the script actually errors out right away because of one errant grammar:
```
/node_modules/first-mate/lib/scope-selector-parser.js:872
      throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
SyntaxError: Expected "(", "-", [ \t], [*], [LRB] or [a-zA-Z0-9+_] but "^" found.
```

I was able to narrow it down to this line:
https://github.com/heyimalex/gh-highlight/blob/6f78e9d9e0d792cf255ffd7ec2c7a9857dfbd2b3/grammars/text.html.php.json#L2467

When I remove that `injection` object, everything works normally. I don't know too much about these grammars, so I don't know if that pattern is disallowed. But removing it definitely fixes things.
